export const RICK_MORTY_API_URL = "https://rickandmortyapi.com/api/character"
export const INSTAGRAM_RICK = "https://www.instagram.com/rickandmorty/"
export const FACEBOOK_RICK = "https://www.facebook.com/RickandMorty/"
export const LINKEDIN_URL = "https://www.linkedin.com/in/yevgeniy-wyszy%C5%84ski/"
export const FLAG_USA_URL = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/United-states_flag_icon_round.svg/1024px-United-states_flag_icon_round.svg.png"
export const FLAG_POLAND_URL = "https://cdn1.iconfinder.com/data/icons/country-flags-11/512/Country_Flags_20-512.png"